language: python
os:
- osx
- linux
python:
- '3.4'
- '3.5'
- 3.6-dev
- nightly
install:
- python setup.py install
- pip install PyYAML
- pip install coverage
- pip install coveralls
script:
- coverage run --source=exchangelib setup.py test
after_success: coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_e7f042a9cf96_key -iv $encrypted_e7f042a9cf96_iv
  -in settings.yml.enc -out settings.yml -d
