from .test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Calendar, Inbox
from exchangelib.items import CalendarItem, Message

class BulkMethodTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_fetch(self) -> None: ...
    def test_bulk_create(self) -> None: ...
    def test_no_account(self) -> None: ...
    def test_empty_args(self) -> None: ...
    def test_qs_args(self) -> None: ...
    def test_no_kwargs(self) -> None: ...
    def test_invalid_bulk_args(self) -> None: ...
    def test_bulk_failure(self) -> None: ...
    def test_bulk_create_with_no_result(self) -> None: ...

class CalendarBulkMethodTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Calendar
    ITEM_CLASS = CalendarItem
    def test_no_account(self) -> None: ...

class MessagesBulkMethodTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_bulk_send(self) -> None: ...
