from ..common import get_random_string as get_random_string
from .test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Inbox
from exchangelib.items import Message

class SyncTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_subscribe_invalid_kwargs(self) -> None: ...
    def test_pull_subscribe(self) -> None: ...
    def test_pull_subscribe_from_account(self) -> None: ...
    def test_push_subscribe(self) -> None: ...
    def test_push_subscribe_from_account(self) -> None: ...
    def test_empty_folder_collection(self) -> None: ...
    def test_streaming_subscribe(self) -> None: ...
    def test_streaming_subscribe_from_account(self) -> None: ...
    def test_sync_folder_hierarchy(self) -> None: ...
    def test_sync_folder_items(self) -> None: ...
    def test_pull_notifications(self) -> None: ...
    def test_streaming_notifications(self) -> None: ...
    def test_streaming_with_other_calls(self) -> None: ...
    def test_streaming_incomplete_generator_consumption(self) -> None: ...
    def test_streaming_invalid_subscription(self) -> None: ...
    def test_push_message_parsing(self) -> None: ...
    def test_push_message_responses(self) -> None: ...
    def test_get_streaming_events_connection_closed(self) -> None: ...
    def test_get_streaming_events_bad_response(self) -> None: ...
