from .test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Inbox
from exchangelib.items import Message

class ItemHelperTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_save_with_update_fields(self) -> None: ...
    def test_soft_delete(self) -> None: ...
    def test_move_to_trash(self) -> None: ...
    def test_copy(self) -> None: ...
    def test_move(self) -> None: ...
    def test_refresh(self) -> None: ...
