from .test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Inbox
from exchangelib.items import Message

class ItemQuerySetTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_querysets(self) -> None: ...
    def test_queryset_failure(self) -> None: ...
    def test_cached_queryset_corner_cases(self) -> None: ...
    def test_queryset_get_by_id(self) -> None: ...
    def test_paging(self) -> None: ...
    def test_slicing(self) -> None: ...
    def test_delete_via_queryset(self) -> None: ...
    def test_send_via_queryset(self) -> None: ...
    def test_send_with_no_copy_via_queryset(self) -> None: ...
    def test_copy_via_queryset(self) -> None: ...
    def test_move_via_queryset(self) -> None: ...
    def test_mark_as_junk_via_queryset(self) -> None: ...
    def test_archive_via_queryset(self) -> None: ...
    def test_depth(self) -> None: ...
    def test_empty_in_sequence(self) -> None: ...
