import abc
import unittest
from _typeshed import Incomplete
from typing import NamedTuple

class mock_account(NamedTuple):
    protocol: Incomplete
    version: Incomplete

class mock_protocol(NamedTuple):
    version: Incomplete
    service_endpoint: Incomplete

class mock_version(NamedTuple):
    build: Incomplete

def get_settings(): ...
def mock_post(url, status_code, headers, text: str = ''): ...
def mock_session_exception(exc_cls): ...

class TimedTestCase(unittest.TestCase, metaclass=abc.ABCMeta):
    SLOW_TEST_DURATION: int
    maxDiff: Incomplete
    t1: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...

class EWSTest(TimedTestCase, metaclass=abc.ABCMeta):
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def credentials(cls): ...
    @classmethod
    def get_account(cls): ...
    categories: Incomplete
    def setUp(self) -> None: ...
    def wipe_test_account(self) -> None: ...
    def bulk_delete(self, ids) -> None: ...
    def random_val(self, field): ...

def get_random_bool(): ...
def get_random_int(min_val: int = 0, max_val: int = 2147483647): ...
def get_random_decimal(min_val: int = 0, max_val: int = 100): ...
def get_random_choice(choices): ...
def get_random_string(length, spaces: bool = True, special: bool = True): ...
def get_random_substring(val): ...
def get_random_byte(): ...
def get_random_bytes(length): ...
def get_random_hostname(): ...
def get_random_url(): ...
def get_random_email(): ...
def get_random_time(start_time=..., end_time=...): ...

RANDOM_DATE_MIN: Incomplete
RANDOM_DATE_MAX: Incomplete
UTC: Incomplete

def get_random_date(start_date=..., end_date=...): ...
def get_random_datetime(start_date=..., end_date=..., tz=...): ...
def get_random_datetime_range(start_date=..., end_date=..., tz=...): ...
