from .common import TimedTestCase as TimedTestCase

class BuildTest(TimedTestCase):
    def test_magic(self) -> None: ...
    def test_compare(self) -> None: ...
    def test_api_version(self) -> None: ...
