from .common import EWSTest as EWSTest, RANDOM_DATE_MAX as RANDOM_DATE_MAX, RANDOM_DATE_MIN as RANDOM_DATE_MIN, get_random_datetime_range as get_random_datetime_range, get_random_hostname as get_random_hostname, get_random_string as get_random_string

class ProtocolTest(EWSTest):
    @staticmethod
    def get_test_protocol(**kwargs): ...
    def test_magic(self) -> None: ...
    def test_close_connections_helper(self) -> None: ...
    def test_init(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_session(self, m) -> None: ...
    def test_protocol_instance_caching(self, m) -> None: ...
    def test_close(self): ...
    def test_decrease_poolsize(self) -> None: ...
    def test_max_usage_count(self) -> None: ...
    def test_get_timezones(self) -> None: ...
    def test_get_timezones_parsing(self) -> None: ...
    def test_get_free_busy_info(self) -> None: ...
    def test_get_roomlists(self) -> None: ...
    def test_get_roomlists_parsing(self) -> None: ...
    def test_get_rooms(self) -> None: ...
    def test_get_rooms_parsing(self) -> None: ...
    def test_resolvenames(self) -> None: ...
    def test_resolvenames_parsing(self) -> None: ...
    def test_resolvenames_warning(self) -> None: ...
    def test_get_searchable_mailboxes(self) -> None: ...
    def test_expanddl(self) -> None: ...
    def test_oof_settings(self) -> None: ...
    def test_oof_settings_validation(self) -> None: ...
    def test_convert_id(self) -> None: ...
    def test_sessionpool(self) -> None: ...
    def test_disable_ssl_verification(self) -> None: ...
    def test_del_on_error(self) -> None: ...
    def test_version_guess(self, m) -> None: ...
    def test_get_service_authtype(self, m) -> None: ...
    def test_get_service_authtype_401(self, m) -> None: ...
    def test_get_service_authtype_501(self, m) -> None: ...
    def test_create_session_failure(self) -> None: ...
    def test_noauth_session(self) -> None: ...
    def test_oauth2_session(self) -> None: ...
