from .common import TimedTestCase as TimedTestCase

class FieldTest(TimedTestCase):
    def test_value_validation(self) -> None: ...
    def test_garbage_input(self) -> None: ...
    def test_versioned_field(self) -> None: ...
    def test_versioned_choice(self) -> None: ...
    def test_date_or_datetime_field(self) -> None: ...
    def test_naive_datetime(self) -> None: ...
    def test_single_field_indexed_element(self) -> None: ...
