from .common import get_random_string as get_random_string
from .test_items.test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Inbox
from exchangelib.items import Message

class AttachmentsTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_magic(self) -> None: ...
    def test_attachment_failure(self) -> None: ...
    def test_file_attachment_properties(self) -> None: ...
    def test_item_attachment_properties(self) -> None: ...
    def test_item_attachments(self): ...
    def test_raw_service_call(self) -> None: ...
    def test_file_attachments(self): ...
    def test_streaming_file_attachments(self) -> None: ...
    def test_streaming_file_attachment_error(self) -> None: ...
    def test_empty_file_attachment(self) -> None: ...
    def test_both_attachment_types(self) -> None: ...
    def test_recursive_attachments(self) -> None: ...
    def test_detach_all(self) -> None: ...
    def test_detach_with_refresh(self) -> None: ...
