from .common import TimedTestCase as TimedTestCase

class VersionTest(TimedTestCase):
    def test_magic(self) -> None: ...
    def test_invalid_version_args(self) -> None: ...
    def test_invalid_build_args(self) -> None: ...
    def test_comparison(self) -> None: ...
    def test_default_api_version(self) -> None: ...
    def test_from_response(self, m) -> None: ...
