from .common import get_random_int as get_random_int, get_random_url as get_random_url
from .test_items.test_basics import BaseItemTest as BaseItemTest
from exchangelib.folders import Inbox
from exchangelib.items import Message

class ExtendedPropertyTest(BaseItemTest):
    TEST_FOLDER: str
    FOLDER_CLASS = Inbox
    ITEM_CLASS = Message
    def test_register(self) -> None: ...
    def test_extended_property_arraytype(self) -> None: ...
    def test_extended_property_with_tag(self) -> None: ...
    def test_extended_property_with_invalid_tag(self) -> None: ...
    def test_extended_property_with_string_tag(self) -> None: ...
    def test_extended_distinguished_property(self) -> None: ...
    def test_extended_property_binary_array(self) -> None: ...
    def test_extended_property_validation(self) -> None: ...
    def test_multiple_extended_properties(self) -> None: ...
    def test_via_queryset(self) -> None: ...
    def test_from_xml(self) -> None: ...
