from .common import TimedTestCase as TimedTestCase, get_settings as get_settings

class EWSDateTimeTest(TimedTestCase):
    def test_super_methods(self) -> None: ...
    def test_ewsdatetime(self) -> None: ...

class EWSTimeZoneTest(TimedTestCase):
    def test_magic(self) -> None: ...
    def test_ewstimezone(self) -> None: ...
    def test_from_timezone(self) -> None: ...
    def test_generate(self) -> None: ...
    def test_generate_failure(self, m) -> None: ...

class EWSDateTest(TimedTestCase):
    def test_ewsdate(self) -> None: ...
