from .common import EWSTest as EWSTest, get_random_email as get_random_email, get_random_hostname as get_random_hostname, get_random_string as get_random_string
from _typeshed import Incomplete

class AutodiscoverTest(EWSTest):
    domain: Incomplete
    dummy_ad_endpoint: Incomplete
    dummy_ews_endpoint: str
    dummy_ad_response: Incomplete
    def setUp(self) -> None: ...
    @staticmethod
    def settings_xml(address, ews_url): ...
    @staticmethod
    def redirect_address_xml(address): ...
    @staticmethod
    def redirect_url_xml(autodiscover_url): ...
    @staticmethod
    def get_test_protocol(**kwargs): ...
    def test_magic(self, m) -> None: ...
    def test_autodiscover_empty_cache(self) -> None: ...
    def test_autodiscover_failure(self) -> None: ...
    def test_failed_login_via_account(self) -> None: ...
    def test_autodiscover_with_delegate(self) -> None: ...
    def test_get_user_settings(self, m) -> None: ...
    def test_close_autodiscover_connections(self, m) -> None: ...
    def test_autodiscover_direct_gc(self, m) -> None: ...
    def test_autodiscover_cache(self, m, *args) -> None: ...
    def test_corrupt_autodiscover_cache(self, m) -> None: ...
    def test_autodiscover_from_account(self, m, *args) -> None: ...
    def test_autodiscover_redirect(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_5(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_3_invalid301_4(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_3_no301_4(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_3_4_valid_srv_invalid_response(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_3_4_valid_srv_valid_response(self, m, *args) -> None: ...
    def test_autodiscover_path_1_2_3_4_invalid_srv(self, m, *args) -> None: ...
    def test_autodiscover_path_1_5_invalid_redirect_url(self, m, *args) -> None: ...
    def test_autodiscover_path_1_5_valid_redirect_url_invalid_response(self, m, *args) -> None: ...
    def test_autodiscover_path_1_5_valid_redirect_url_valid_response(self, m, *args) -> None: ...
    def test_get_srv_records(self): ...
    def test_srv_magic(self) -> None: ...
    def test_select_srv_host(self) -> None: ...
    def test_raise_errors(self) -> None: ...
    def test_del_on_error(self) -> None: ...
    def test_shelve_filename(self) -> None: ...
    def test_shelve_filename_getuser_failure(self, m) -> None: ...
    def test_redirect_url_is_valid(self, m) -> None: ...
    def test_protocol_default_values(self) -> None: ...
