from .common import EWSTest as EWSTest, mock_post as mock_post, mock_session_exception as mock_session_exception

class UtilTest(EWSTest):
    def test_chunkify(self) -> None: ...
    def test_peek(self) -> None: ...
    def test_get_redirect_url(self, m) -> None: ...
    def test_to_xml(self) -> None: ...
    def test_to_xml_failure(self, m) -> None: ...
    def test_to_xml_failure_2(self, m) -> None: ...
    def test_to_xml_failure_3(self, m) -> None: ...
    def test_is_xml(self) -> None: ...
    def test_xml_to_str(self) -> None: ...
    def test_streaming_parser(self) -> None: ...
    def test_anonymizing_handler(self) -> None: ...
    def test_get_domain(self) -> None: ...
    def test_pretty_xml_handler(self): ...
    def test_post_ratelimited(self): ...
    def test_safe_b64decode(self) -> None: ...
    def test_document_yielder(self) -> None: ...
