from .common import TimedTestCase as TimedTestCase

class QuerySetTest(TimedTestCase):
    def test_magic(self) -> None: ...
    def test_from_folder(self) -> None: ...
    def test_queryset_copy(self) -> None: ...
