from .common import TimedTestCase as TimedTestCase

class PropertiesTest(TimedTestCase):
    def test_ews_element_sanity(self) -> None: ...
    def test_uid(self) -> None: ...
    def test_internet_message_headers(self) -> None: ...
    def test_physical_address(self) -> None: ...
    def test_invalid_kwargs(self) -> None: ...
    def test_invalid_field(self) -> None: ...
    def test_add_field(self) -> None: ...
    def test_itemid_equality(self) -> None: ...
    def test_mailbox(self) -> None: ...
    def test_body(self) -> None: ...
    def test_invalid_attribute(self) -> None: ...
    def test_fields(self) -> None: ...
