from .common import EWSTest as EWSTest, get_random_bool as get_random_bool, get_random_byte as get_random_byte, get_random_bytes as get_random_bytes, get_random_datetime as get_random_datetime, get_random_int as get_random_int, get_random_string as get_random_string

def get_random_str_tuple(tuple_length, str_length): ...

class FolderTest(EWSTest):
    def test_folders(self) -> None: ...
    def test_folder_failure(self) -> None: ...
    def test_public_folders_root(self, m) -> None: ...
    def test_invalid_deletefolder_args(self) -> None: ...
    def test_invalid_emptyfolder_args(self) -> None: ...
    def test_invalid_findfolder_args(self) -> None: ...
    def test_find_folders(self) -> None: ...
    def test_find_folders_multiple_roots(self) -> None: ...
    def test_find_folders_compat(self) -> None: ...
    def test_find_folders_with_restriction(self) -> None: ...
    def test_get_folders(self) -> None: ...
    def test_shared_folders(self) -> None: ...
    def test_folder_grouping(self) -> None: ...
    def test_counts(self) -> None: ...
    def test_case_sensitivity(self) -> None: ...
    def test_update(self) -> None: ...
    def test_refresh(self) -> None: ...
    def test_parent(self) -> None: ...
    def test_children(self) -> None: ...
    def test_parts(self) -> None: ...
    def test_absolute(self) -> None: ...
    def test_walk(self) -> None: ...
    def test_tree(self) -> None: ...
    def test_glob(self) -> None: ...
    def test_collection_filtering(self) -> None: ...
    def test_empty_collections(self) -> None: ...
    def test_div_navigation(self) -> None: ...
    def test_double_div_navigation(self) -> None: ...
    def test_extended_properties(self) -> None: ...
    def test_create_update_empty_delete(self) -> None: ...
    def test_folder_type_guessing(self) -> None: ...
    def test_wipe_without_empty(self) -> None: ...
    def test_move(self) -> None: ...
    def test_generic_folder(self) -> None: ...
    def test_non_deletable_folders(self) -> None: ...
    def test_folder_collections(self) -> None: ...
    def test_folder_query_set(self) -> None: ...
    def test_folder_query_set_failures(self) -> None: ...
    def test_user_configuration(self) -> None: ...
    def test_permissionset_effectiverights_parsing(self) -> None: ...
    def test_get_candidate(self) -> None: ...
