from .common import TimedTestCase as TimedTestCase

class CredentialsTest(TimedTestCase):
    def test_hash(self) -> None: ...
    def test_equality(self) -> None: ...
    def test_type(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_plain(self) -> None: ...
    def test_oauth_validation(self) -> None: ...
