from _typeshed import Incomplete

class MultipleObjectsReturned(Exception): ...
class DoesNotExist(Exception): ...

class InvalidEnumValue(ValueError):
    field_name: Incomplete
    value: Incomplete
    choices: Incomplete
    def __init__(self, field_name, value, choices) -> None: ...

class InvalidTypeError(TypeError):
    field_name: Incomplete
    value: Incomplete
    valid_type: Incomplete
    def __init__(self, field_name, value, valid_type) -> None: ...

class EWSError(Exception):
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class EWSWarning(EWSError): ...
class TransportError(EWSError): ...

class RateLimitError(TransportError):
    wait: Incomplete
    def __init__(self, value, wait) -> None: ...

class SOAPError(TransportError): ...
class MalformedResponseError(TransportError): ...
class UnauthorizedError(EWSError): ...

class RedirectError(TransportError):
    url: Incomplete
    server: Incomplete
    has_ssl: Incomplete
    def __init__(self, url) -> None: ...

class RelativeRedirect(TransportError): ...
class AutoDiscoverError(TransportError): ...
class AutoDiscoverFailed(AutoDiscoverError): ...
class AutoDiscoverCircularRedirect(AutoDiscoverError): ...

class NaiveDateTimeNotAllowed(ValueError):
    local_dt: Incomplete
    def __init__(self, local_dt) -> None: ...

class UnknownTimeZone(EWSError): ...
class SessionPoolMinSizeReached(EWSError): ...
class SessionPoolMaxSizeReached(EWSError): ...
class ResponseMessageError(TransportError): ...

class CASError(EWSError):
    cas_error: Incomplete
    response: Incomplete
    def __init__(self, cas_error, response) -> None: ...

class ErrorAccessDenied(ResponseMessageError): ...
class ErrorAccessModeSpecified(ResponseMessageError): ...
class ErrorAccountDisabled(ResponseMessageError): ...
class ErrorAddDelegatesFailed(ResponseMessageError): ...
class ErrorAddressSpaceNotFound(ResponseMessageError): ...
class ErrorADOperation(ResponseMessageError): ...
class ErrorADSessionFilter(ResponseMessageError): ...
class ErrorADUnavailable(ResponseMessageError): ...
class ErrorAffectedTaskOccurrencesRequired(ResponseMessageError): ...
class ErrorApplyConversationActionFailed(ResponseMessageError): ...
class ErrorAttachmentSizeLimitExceeded(ResponseMessageError): ...
class ErrorAutoDiscoverFailed(ResponseMessageError): ...
class ErrorAvailabilityConfigNotFound(ResponseMessageError): ...
class ErrorBatchProcessingStopped(ResponseMessageError): ...
class ErrorCalendarCannotMoveOrCopyOccurrence(ResponseMessageError): ...
class ErrorCalendarCannotUpdateDeletedItem(ResponseMessageError): ...
class ErrorCalendarCannotUseIdForOccurrenceId(ResponseMessageError): ...
class ErrorCalendarCannotUseIdForRecurringMasterId(ResponseMessageError): ...
class ErrorCalendarDurationIsTooLong(ResponseMessageError): ...
class ErrorCalendarEndDateIsEarlierThanStartDate(ResponseMessageError): ...
class ErrorCalendarFolderIsInvalidForCalendarView(ResponseMessageError): ...
class ErrorCalendarInvalidAttributeValue(ResponseMessageError): ...
class ErrorCalendarInvalidDayForTimeChangePattern(ResponseMessageError): ...
class ErrorCalendarInvalidDayForWeeklyRecurrence(ResponseMessageError): ...
class ErrorCalendarInvalidPropertyState(ResponseMessageError): ...
class ErrorCalendarInvalidPropertyValue(ResponseMessageError): ...
class ErrorCalendarInvalidRecurrence(ResponseMessageError): ...
class ErrorCalendarInvalidTimeZone(ResponseMessageError): ...
class ErrorCalendarIsCancelledForAccept(ResponseMessageError): ...
class ErrorCalendarIsCancelledForDecline(ResponseMessageError): ...
class ErrorCalendarIsCancelledForRemove(ResponseMessageError): ...
class ErrorCalendarIsCancelledForTentative(ResponseMessageError): ...
class ErrorCalendarIsDelegatedForAccept(ResponseMessageError): ...
class ErrorCalendarIsDelegatedForDecline(ResponseMessageError): ...
class ErrorCalendarIsDelegatedForRemove(ResponseMessageError): ...
class ErrorCalendarIsDelegatedForTentative(ResponseMessageError): ...
class ErrorCalendarIsNotOrganizer(ResponseMessageError): ...
class ErrorCalendarIsOrganizerForAccept(ResponseMessageError): ...
class ErrorCalendarIsOrganizerForDecline(ResponseMessageError): ...
class ErrorCalendarIsOrganizerForRemove(ResponseMessageError): ...
class ErrorCalendarIsOrganizerForTentative(ResponseMessageError): ...
class ErrorCalendarMeetingRequestIsOutOfDate(ResponseMessageError): ...
class ErrorCalendarOccurrenceIndexIsOutOfRecurrenceRange(ResponseMessageError): ...
class ErrorCalendarOccurrenceIsDeletedFromRecurrence(ResponseMessageError): ...
class ErrorCalendarOutOfRange(ResponseMessageError): ...
class ErrorCalendarViewRangeTooBig(ResponseMessageError): ...
class ErrorCallerIsInvalidADAccount(ResponseMessageError): ...
class ErrorCannotCreateCalendarItemInNonCalendarFolder(ResponseMessageError): ...
class ErrorCannotCreateContactInNonContactFolder(ResponseMessageError): ...
class ErrorCannotCreatePostItemInNonMailFolder(ResponseMessageError): ...
class ErrorCannotCreateTaskInNonTaskFolder(ResponseMessageError): ...
class ErrorCannotDeleteObject(ResponseMessageError): ...
class ErrorCannotDeleteTaskOccurrence(ResponseMessageError): ...
class ErrorCannotEmptyFolder(ResponseMessageError): ...
class ErrorCannotOpenFileAttachment(ResponseMessageError): ...
class ErrorCannotSetCalendarPermissionOnNonCalendarFolder(ResponseMessageError): ...
class ErrorCannotSetNonCalendarPermissionOnCalendarFolder(ResponseMessageError): ...
class ErrorCannotSetPermissionUnknownEntries(ResponseMessageError): ...
class ErrorCannotUseFolderIdForItemId(ResponseMessageError): ...
class ErrorCannotUseItemIdForFolderId(ResponseMessageError): ...
class ErrorChangeKeyRequired(ResponseMessageError): ...
class ErrorChangeKeyRequiredForWriteOperations(ResponseMessageError): ...
class ErrorClientDisconnected(ResponseMessageError): ...
class ErrorConnectionFailed(ResponseMessageError): ...
class ErrorConnectionFailedTransientError(ResponseMessageError): ...
class ErrorContainsFilterWrongType(ResponseMessageError): ...
class ErrorContentConversionFailed(ResponseMessageError): ...
class ErrorCorruptData(ResponseMessageError): ...
class ErrorCreateItemAccessDenied(ResponseMessageError): ...
class ErrorCreateManagedFolderPartialCompletion(ResponseMessageError): ...
class ErrorCreateSubfolderAccessDenied(ResponseMessageError): ...
class ErrorCrossMailboxMoveCopy(ResponseMessageError): ...
class ErrorCrossSiteRequest(ResponseMessageError): ...
class ErrorDataSizeLimitExceeded(ResponseMessageError): ...
class ErrorDataSourceOperation(ResponseMessageError): ...
class ErrorDelegateAlreadyExists(ResponseMessageError): ...
class ErrorDelegateCannotAddOwner(ResponseMessageError): ...
class ErrorDelegateMissingConfiguration(ResponseMessageError): ...
class ErrorDelegateNoUser(ResponseMessageError): ...
class ErrorDelegateValidationFailed(ResponseMessageError): ...
class ErrorDeleteDistinguishedFolder(ResponseMessageError): ...
class ErrorDeleteItemsFailed(ResponseMessageError): ...
class ErrorDistinguishedUserNotSupported(ResponseMessageError): ...
class ErrorDistributionListMemberNotExist(ResponseMessageError): ...
class ErrorDuplicateInputFolderNames(ResponseMessageError): ...
class ErrorDuplicateSOAPHeader(ResponseMessageError): ...
class ErrorDuplicateUserIdsSpecified(ResponseMessageError): ...
class ErrorEmailAddressMismatch(ResponseMessageError): ...
class ErrorEventNotFound(ResponseMessageError): ...
class ErrorExceededConnectionCount(ResponseMessageError): ...
class ErrorExceededFindCountLimit(ResponseMessageError): ...
class ErrorExceededSubscriptionCount(ResponseMessageError): ...
class ErrorExpiredSubscription(ResponseMessageError): ...
class ErrorFolderCorrupt(ResponseMessageError): ...
class ErrorFolderExists(ResponseMessageError): ...
class ErrorFolderNotFound(ResponseMessageError): ...
class ErrorFolderPropertyRequestFailed(ResponseMessageError): ...
class ErrorFolderSave(ResponseMessageError): ...
class ErrorFolderSaveFailed(ResponseMessageError): ...
class ErrorFolderSavePropertyError(ResponseMessageError): ...
class ErrorFreeBusyDLLimitReached(ResponseMessageError): ...
class ErrorFreeBusyGenerationFailed(ResponseMessageError): ...
class ErrorGetServerSecurityDescriptorFailed(ResponseMessageError): ...
class ErrorImpersonateUserDenied(ResponseMessageError): ...
class ErrorImpersonationDenied(ResponseMessageError): ...
class ErrorImpersonationFailed(ResponseMessageError): ...
class ErrorInboxRulesValidationError(ResponseMessageError): ...
class ErrorIncorrectSchemaVersion(ResponseMessageError): ...
class ErrorIncorrectUpdatePropertyCount(ResponseMessageError): ...
class ErrorIndividualMailboxLimitReached(ResponseMessageError): ...
class ErrorInsufficientResources(ResponseMessageError): ...
class ErrorInternalServerError(ResponseMessageError): ...
class ErrorInternalServerTransientError(ResponseMessageError): ...
class ErrorInvalidAccessLevel(ResponseMessageError): ...
class ErrorInvalidArgument(ResponseMessageError): ...
class ErrorInvalidAttachmentId(ResponseMessageError): ...
class ErrorInvalidAttachmentSubfilter(ResponseMessageError): ...
class ErrorInvalidAttachmentSubfilterTextFilter(ResponseMessageError): ...
class ErrorInvalidAuthorizationContext(ResponseMessageError): ...
class ErrorInvalidChangeKey(ResponseMessageError): ...
class ErrorInvalidClientSecurityContext(ResponseMessageError): ...
class ErrorInvalidCompleteDate(ResponseMessageError): ...
class ErrorInvalidContactEmailAddress(ResponseMessageError): ...
class ErrorInvalidContactEmailIndex(ResponseMessageError): ...
class ErrorInvalidCrossForestCredentials(ResponseMessageError): ...
class ErrorInvalidDelegatePermission(ResponseMessageError): ...
class ErrorInvalidDelegateUserId(ResponseMessageError): ...
class ErrorInvalidExchangeImpersonationHeaderData(ResponseMessageError): ...
class ErrorInvalidExcludesRestriction(ResponseMessageError): ...
class ErrorInvalidExpressionTypeForSubFilter(ResponseMessageError): ...
class ErrorInvalidExtendedProperty(ResponseMessageError): ...
class ErrorInvalidExtendedPropertyValue(ResponseMessageError): ...
class ErrorInvalidExternalSharingInitiator(ResponseMessageError): ...
class ErrorInvalidExternalSharingSubscriber(ResponseMessageError): ...
class ErrorInvalidFederatedOrganizationId(ResponseMessageError): ...
class ErrorInvalidFolderId(ResponseMessageError): ...
class ErrorInvalidFolderTypeForOperation(ResponseMessageError): ...
class ErrorInvalidFractionalPagingParameters(ResponseMessageError): ...
class ErrorInvalidFreeBusyViewType(ResponseMessageError): ...
class ErrorInvalidGetSharingFolderRequest(ResponseMessageError): ...
class ErrorInvalidId(ResponseMessageError): ...
class ErrorInvalidIdEmpty(ResponseMessageError): ...
class ErrorInvalidIdMalformed(ResponseMessageError): ...
class ErrorInvalidIdMalformedEwsLegacyIdFormat(ResponseMessageError): ...
class ErrorInvalidIdMonikerTooLong(ResponseMessageError): ...
class ErrorInvalidIdNotAnItemAttachmentId(ResponseMessageError): ...
class ErrorInvalidIdReturnedByResolveNames(ResponseMessageError): ...
class ErrorInvalidIdStoreObjectIdTooLong(ResponseMessageError): ...
class ErrorInvalidIdTooManyAttachmentLevels(ResponseMessageError): ...
class ErrorInvalidIdXml(ResponseMessageError): ...
class ErrorInvalidIndexedPagingParameters(ResponseMessageError): ...
class ErrorInvalidInternetHeaderChildNodes(ResponseMessageError): ...
class ErrorInvalidItemForOperationAcceptItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationCancelItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationCreateItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationCreateItemAttachment(ResponseMessageError): ...
class ErrorInvalidItemForOperationDeclineItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationExpandDL(ResponseMessageError): ...
class ErrorInvalidItemForOperationRemoveItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationSendItem(ResponseMessageError): ...
class ErrorInvalidItemForOperationTentative(ResponseMessageError): ...
class ErrorInvalidLicense(ResponseMessageError): ...
class ErrorInvalidLogonType(ResponseMessageError): ...
class ErrorInvalidMailbox(ResponseMessageError): ...
class ErrorInvalidManagedFolderProperty(ResponseMessageError): ...
class ErrorInvalidManagedFolderQuota(ResponseMessageError): ...
class ErrorInvalidManagedFolderSize(ResponseMessageError): ...
class ErrorInvalidMergedFreeBusyInterval(ResponseMessageError): ...
class ErrorInvalidNameForNameResolution(ResponseMessageError): ...
class ErrorInvalidNetworkServiceContext(ResponseMessageError): ...
class ErrorInvalidOofParameter(ResponseMessageError): ...
class ErrorInvalidOperation(ResponseMessageError): ...
class ErrorInvalidOrganizationRelationshipForFreeBusy(ResponseMessageError): ...
class ErrorInvalidPagingMaxRows(ResponseMessageError): ...
class ErrorInvalidParentFolder(ResponseMessageError): ...
class ErrorInvalidPercentCompleteValue(ResponseMessageError): ...
class ErrorInvalidPermissionSettings(ResponseMessageError): ...
class ErrorInvalidPhoneCallId(ResponseMessageError): ...
class ErrorInvalidPhoneNumber(ResponseMessageError): ...
class ErrorInvalidPropertyAppend(ResponseMessageError): ...
class ErrorInvalidPropertyDelete(ResponseMessageError): ...
class ErrorInvalidPropertyForExists(ResponseMessageError): ...
class ErrorInvalidPropertyForOperation(ResponseMessageError): ...
class ErrorInvalidPropertyRequest(ResponseMessageError): ...
class ErrorInvalidPropertySet(ResponseMessageError): ...
class ErrorInvalidPropertyUpdateSentMessage(ResponseMessageError): ...
class ErrorInvalidProxySecurityContext(ResponseMessageError): ...
class ErrorInvalidPullSubscriptionId(ResponseMessageError): ...
class ErrorInvalidPushSubscriptionUrl(ResponseMessageError): ...
class ErrorInvalidRecipients(ResponseMessageError): ...
class ErrorInvalidRecipientSubfilter(ResponseMessageError): ...
class ErrorInvalidRecipientSubfilterComparison(ResponseMessageError): ...
class ErrorInvalidRecipientSubfilterOrder(ResponseMessageError): ...
class ErrorInvalidRecipientSubfilterTextFilter(ResponseMessageError): ...
class ErrorInvalidReferenceItem(ResponseMessageError): ...
class ErrorInvalidRequest(ResponseMessageError): ...
class ErrorInvalidRestriction(ResponseMessageError): ...
class ErrorInvalidRoutingType(ResponseMessageError): ...
class ErrorInvalidScheduledOofDuration(ResponseMessageError): ...
class ErrorInvalidSchemaVersionForMailboxVersion(ResponseMessageError): ...
class ErrorInvalidSecurityDescriptor(ResponseMessageError): ...
class ErrorInvalidSendItemSaveSettings(ResponseMessageError): ...
class ErrorInvalidSerializedAccessToken(ResponseMessageError): ...
class ErrorInvalidServerVersion(ResponseMessageError): ...
class ErrorInvalidSharingData(ResponseMessageError): ...
class ErrorInvalidSharingMessage(ResponseMessageError): ...
class ErrorInvalidSid(ResponseMessageError): ...
class ErrorInvalidSIPUri(ResponseMessageError): ...
class ErrorInvalidSmtpAddress(ResponseMessageError): ...
class ErrorInvalidSubfilterType(ResponseMessageError): ...
class ErrorInvalidSubfilterTypeNotAttendeeType(ResponseMessageError): ...
class ErrorInvalidSubfilterTypeNotRecipientType(ResponseMessageError): ...
class ErrorInvalidSubscription(ResponseMessageError): ...
class ErrorInvalidSubscriptionRequest(ResponseMessageError): ...
class ErrorInvalidSyncStateData(ResponseMessageError): ...
class ErrorInvalidTimeInterval(ResponseMessageError): ...
class ErrorInvalidUserInfo(ResponseMessageError): ...
class ErrorInvalidUserOofSettings(ResponseMessageError): ...
class ErrorInvalidUserPrincipalName(ResponseMessageError): ...
class ErrorInvalidUserSid(ResponseMessageError): ...
class ErrorInvalidUserSidMissingUPN(ResponseMessageError): ...
class ErrorInvalidValueForProperty(ResponseMessageError): ...
class ErrorInvalidWatermark(ResponseMessageError): ...
class ErrorIPGatewayNotFound(ResponseMessageError): ...
class ErrorIrresolvableConflict(ResponseMessageError): ...
class ErrorItemCorrupt(ResponseMessageError): ...
class ErrorItemNotFound(ResponseMessageError): ...
class ErrorItemPropertyRequestFailed(ResponseMessageError): ...
class ErrorItemSave(ResponseMessageError): ...
class ErrorItemSavePropertyError(ResponseMessageError): ...
class ErrorLegacyMailboxFreeBusyViewTypeNotMerged(ResponseMessageError): ...
class ErrorLocalServerObjectNotFound(ResponseMessageError): ...
class ErrorLogonAsNetworkServiceFailed(ResponseMessageError): ...
class ErrorMailboxConfiguration(ResponseMessageError): ...
class ErrorMailboxDataArrayEmpty(ResponseMessageError): ...
class ErrorMailboxDataArrayTooBig(ResponseMessageError): ...
class ErrorMailboxFailover(ResponseMessageError): ...
class ErrorMailboxLogonFailed(ResponseMessageError): ...
class ErrorMailboxMoveInProgress(ResponseMessageError): ...
class ErrorMailboxStoreUnavailable(ResponseMessageError): ...
class ErrorMailRecipientNotFound(ResponseMessageError): ...
class ErrorMailTipsDisabled(ResponseMessageError): ...
class ErrorManagedFolderAlreadyExists(ResponseMessageError): ...
class ErrorManagedFolderNotFound(ResponseMessageError): ...
class ErrorManagedFoldersRootFailure(ResponseMessageError): ...
class ErrorMeetingSuggestionGenerationFailed(ResponseMessageError): ...
class ErrorMessageDispositionRequired(ResponseMessageError): ...
class ErrorMessageSizeExceeded(ResponseMessageError): ...
class ErrorMessageTrackingNoSuchDomain(ResponseMessageError): ...
class ErrorMessageTrackingPermanentError(ResponseMessageError): ...
class ErrorMessageTrackingTransientError(ResponseMessageError): ...
class ErrorMimeContentConversionFailed(ResponseMessageError): ...
class ErrorMimeContentInvalid(ResponseMessageError): ...
class ErrorMimeContentInvalidBase64String(ResponseMessageError): ...
class ErrorMissedNotificationEvents(ResponseMessageError): ...
class ErrorMissingArgument(ResponseMessageError): ...
class ErrorMissingEmailAddress(ResponseMessageError): ...
class ErrorMissingEmailAddressForManagedFolder(ResponseMessageError): ...
class ErrorMissingInformationEmailAddress(ResponseMessageError): ...
class ErrorMissingInformationReferenceItemId(ResponseMessageError): ...
class ErrorMissingInformationSharingFolderId(ResponseMessageError): ...
class ErrorMissingItemForCreateItemAttachment(ResponseMessageError): ...
class ErrorMissingManagedFolderId(ResponseMessageError): ...
class ErrorMissingRecipients(ResponseMessageError): ...
class ErrorMissingUserIdInformation(ResponseMessageError): ...
class ErrorMoreThanOneAccessModeSpecified(ResponseMessageError): ...
class ErrorMoveCopyFailed(ResponseMessageError): ...
class ErrorMoveDistinguishedFolder(ResponseMessageError): ...
class ErrorNameResolutionMultipleResults(ResponseMessageError): ...
class ErrorNameResolutionNoMailbox(ResponseMessageError): ...
class ErrorNameResolutionNoResults(ResponseMessageError): ...
class ErrorNewEventStreamConnectionOpened(ResponseMessageError): ...
class ErrorNoApplicableProxyCASServersAvailable(ResponseMessageError): ...
class ErrorNoCalendar(ResponseMessageError): ...
class ErrorNoDestinationCASDueToKerberosRequirements(ResponseMessageError): ...
class ErrorNoDestinationCASDueToSSLRequirements(ResponseMessageError): ...
class ErrorNoDestinationCASDueToVersionMismatch(ResponseMessageError): ...
class ErrorNoFolderClassOverride(ResponseMessageError): ...
class ErrorNoFreeBusyAccess(ResponseMessageError): ...
class ErrorNonExistentMailbox(ResponseMessageError): ...
class ErrorNonPrimarySmtpAddress(ResponseMessageError): ...
class ErrorNoPropertyTagForCustomProperties(ResponseMessageError): ...
class ErrorNoPublicFolderReplicaAvailable(ResponseMessageError): ...
class ErrorNoPublicFolderServerAvailable(ResponseMessageError): ...
class ErrorNoRespondingCASInDestinationSite(ResponseMessageError): ...
class ErrorNotAllowedExternalSharingByPolicy(ResponseMessageError): ...
class ErrorNotDelegate(ResponseMessageError): ...
class ErrorNotEnoughMemory(ResponseMessageError): ...
class ErrorNotSupportedSharingMessage(ResponseMessageError): ...
class ErrorObjectTypeChanged(ResponseMessageError): ...
class ErrorOccurrenceCrossingBoundary(ResponseMessageError): ...
class ErrorOccurrenceTimeSpanTooBig(ResponseMessageError): ...
class ErrorOperationNotAllowedWithPublicFolderRoot(ResponseMessageError): ...
class ErrorOrganizationNotFederated(ResponseMessageError): ...
class ErrorOutlookRuleBlobExists(ResponseMessageError): ...
class ErrorParentFolderIdRequired(ResponseMessageError): ...
class ErrorParentFolderNotFound(ResponseMessageError): ...
class ErrorPasswordChangeRequired(ResponseMessageError): ...
class ErrorPasswordExpired(ResponseMessageError): ...
class ErrorPermissionNotAllowedByPolicy(ResponseMessageError): ...
class ErrorPhoneNumberNotDialable(ResponseMessageError): ...
class ErrorPropertyUpdate(ResponseMessageError): ...
class ErrorPropertyValidationFailure(ResponseMessageError): ...
class ErrorProxiedSubscriptionCallFailure(ResponseMessageError): ...
class ErrorProxyCallFailed(ResponseMessageError): ...
class ErrorProxyGroupSidLimitExceeded(ResponseMessageError): ...
class ErrorProxyRequestNotAllowed(ResponseMessageError): ...
class ErrorProxyRequestProcessingFailed(ResponseMessageError): ...
class ErrorProxyServiceDiscoveryFailed(ResponseMessageError): ...
class ErrorProxyTokenExpired(ResponseMessageError): ...
class ErrorPublicFolderRequestProcessingFailed(ResponseMessageError): ...
class ErrorPublicFolderServerNotFound(ResponseMessageError): ...
class ErrorQueryFilterTooLong(ResponseMessageError): ...
class ErrorQuotaExceeded(ResponseMessageError): ...
class ErrorReadEventsFailed(ResponseMessageError): ...
class ErrorReadReceiptNotPending(ResponseMessageError): ...
class ErrorRecoverableItemsAccessDenied(ResponseMessageError): ...
class ErrorRecurrenceEndDateTooBig(ResponseMessageError): ...
class ErrorRecurrenceHasNoOccurrence(ResponseMessageError): ...
class ErrorRemoveDelegatesFailed(ResponseMessageError): ...
class ErrorRequestAborted(ResponseMessageError): ...
class ErrorRequestStreamTooBig(ResponseMessageError): ...
class ErrorRequiredPropertyMissing(ResponseMessageError): ...
class ErrorResolveNamesInvalidFolderType(ResponseMessageError): ...
class ErrorResolveNamesOnlyOneContactsFolderAllowed(ResponseMessageError): ...
class ErrorResponseSchemaValidation(ResponseMessageError): ...
class ErrorRestrictionTooComplex(ResponseMessageError): ...
class ErrorRestrictionTooLong(ResponseMessageError): ...
class ErrorResultSetTooBig(ResponseMessageError): ...
class ErrorRulesOverQuota(ResponseMessageError): ...
class ErrorSavedItemFolderNotFound(ResponseMessageError): ...
class ErrorSchemaValidation(ResponseMessageError): ...
class ErrorSearchFolderNotInitialized(ResponseMessageError): ...
class ErrorSendAsDenied(ResponseMessageError): ...
class ErrorSendMeetingCancellationsRequired(ResponseMessageError): ...
class ErrorSendMeetingInvitationsOrCancellationsRequired(ResponseMessageError): ...
class ErrorSendMeetingInvitationsRequired(ResponseMessageError): ...
class ErrorSentMeetingRequestUpdate(ResponseMessageError): ...
class ErrorSentTaskRequestUpdate(ResponseMessageError): ...

class ErrorServerBusy(ResponseMessageError):
    back_off: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class ErrorServiceDiscoveryFailed(ResponseMessageError): ...
class ErrorSharingNoExternalEwsAvailable(ResponseMessageError): ...
class ErrorSharingSynchronizationFailed(ResponseMessageError): ...
class ErrorStaleObject(ResponseMessageError): ...
class ErrorSubmissionQuotaExceeded(ResponseMessageError): ...
class ErrorSubscriptionAccessDenied(ResponseMessageError): ...
class ErrorSubscriptionDelegateAccessNotSupported(ResponseMessageError): ...
class ErrorSubscriptionNotFound(ResponseMessageError): ...
class ErrorSubscriptionUnsubsribed(ResponseMessageError): ...
class ErrorSyncFolderNotFound(ResponseMessageError): ...
class ErrorTimeIntervalTooBig(ResponseMessageError): ...
class ErrorTimeoutExpired(ResponseMessageError): ...
class ErrorTimeZone(ResponseMessageError): ...
class ErrorToFolderNotFound(ResponseMessageError): ...
class ErrorTokenSerializationDenied(ResponseMessageError): ...
class ErrorTooManyObjectsOpened(ResponseMessageError): ...
class ErrorUnableToGetUserOofSettings(ResponseMessageError): ...
class ErrorUnifiedMessagingDialPlanNotFound(ResponseMessageError): ...
class ErrorUnifiedMessagingRequestFailed(ResponseMessageError): ...
class ErrorUnifiedMessagingServerNotFound(ResponseMessageError): ...
class ErrorUnsupportedCulture(ResponseMessageError): ...
class ErrorUnsupportedMapiPropertyType(ResponseMessageError): ...
class ErrorUnsupportedMimeConversion(ResponseMessageError): ...
class ErrorUnsupportedPathForQuery(ResponseMessageError): ...
class ErrorUnsupportedPathForSortGroup(ResponseMessageError): ...
class ErrorUnsupportedPropertyDefinition(ResponseMessageError): ...
class ErrorUnsupportedQueryFilter(ResponseMessageError): ...
class ErrorUnsupportedRecurrence(ResponseMessageError): ...
class ErrorUnsupportedSubFilter(ResponseMessageError): ...
class ErrorUnsupportedTypeForConversion(ResponseMessageError): ...
class ErrorUpdateDelegatesFailed(ResponseMessageError): ...
class ErrorUpdatePropertyMismatch(ResponseMessageError): ...
class ErrorUserNotAllowedByPolicy(ResponseMessageError): ...
class ErrorUserNotUnifiedMessagingEnabled(ResponseMessageError): ...
class ErrorUserWithoutFederatedProxyAddress(ResponseMessageError): ...
class ErrorValueOutOfRange(ResponseMessageError): ...
class ErrorVirusDetected(ResponseMessageError): ...
class ErrorVirusMessageDeleted(ResponseMessageError): ...
class ErrorVoiceMailNotImplemented(ResponseMessageError): ...
class ErrorWebRequestInInvalidState(ResponseMessageError): ...
class ErrorWin32InteropError(ResponseMessageError): ...
class ErrorWorkingHoursSaveFailed(ResponseMessageError): ...
class ErrorWorkingHoursXmlMalformed(ResponseMessageError): ...
class ErrorWrongServerVersion(ResponseMessageError): ...
class ErrorWrongServerVersionDelegate(ResponseMessageError): ...

ERRORS_REQUIRING_REAUTODISCOVER: Incomplete
