from .base import AFFECTED_TASK_OCCURRENCES_CHOICES as AFFECTED_TASK_OCCURRENCES_CHOICES, ALL_OCCURRENCES as ALL_OCCURRENCES, ALL_PROPERTIES as ALL_PROPERTIES, ALWAYS_OVERWRITE as ALWAYS_OVERWRITE, AUTO_RESOLVE as AUTO_RESOLVE, BulkCreateResult as BulkCreateResult, CONFLICT_RESOLUTION_CHOICES as CONFLICT_RESOLUTION_CHOICES, DEFAULT as DEFAULT, DELETE_TYPE_CHOICES as DELETE_TYPE_CHOICES, HARD_DELETE as HARD_DELETE, ID_ONLY as ID_ONLY, MESSAGE_DISPOSITION_CHOICES as MESSAGE_DISPOSITION_CHOICES, MOVE_TO_DELETED_ITEMS as MOVE_TO_DELETED_ITEMS, NEVER_OVERWRITE as NEVER_OVERWRITE, RegisterMixIn as RegisterMixIn, SAVE_ONLY as SAVE_ONLY, SEND_AND_SAVE_COPY as SEND_AND_SAVE_COPY, SEND_MEETING_CANCELLATIONS_CHOICES as SEND_MEETING_CANCELLATIONS_CHOICES, SEND_MEETING_INVITATIONS_AND_CANCELLATIONS_CHOICES as SEND_MEETING_INVITATIONS_AND_CANCELLATIONS_CHOICES, SEND_MEETING_INVITATIONS_CHOICES as SEND_MEETING_INVITATIONS_CHOICES, SEND_ONLY as SEND_ONLY, SEND_ONLY_TO_ALL as SEND_ONLY_TO_ALL, SEND_ONLY_TO_CHANGED as SEND_ONLY_TO_CHANGED, SEND_TO_ALL_AND_SAVE_COPY as SEND_TO_ALL_AND_SAVE_COPY, SEND_TO_CHANGED_AND_SAVE_COPY as SEND_TO_CHANGED_AND_SAVE_COPY, SEND_TO_NONE as SEND_TO_NONE, SHAPE_CHOICES as SHAPE_CHOICES, SOFT_DELETE as SOFT_DELETE, SPECIFIED_OCCURRENCE_ONLY as SPECIFIED_OCCURRENCE_ONLY
from .calendar_item import AcceptItem as AcceptItem, CONFERENCE_TYPES as CONFERENCE_TYPES, CalendarItem as CalendarItem, CancelCalendarItem as CancelCalendarItem, DeclineItem as DeclineItem, MeetingCancellation as MeetingCancellation, MeetingRequest as MeetingRequest, MeetingResponse as MeetingResponse, TentativelyAcceptItem as TentativelyAcceptItem
from .contact import Contact as Contact, DistributionList as DistributionList, Persona as Persona
from .item import BaseItem as BaseItem, Item as Item
from .message import ForwardItem as ForwardItem, Message as Message, ReplyAllToItem as ReplyAllToItem, ReplyToItem as ReplyToItem
from .post import PostItem as PostItem, PostReplyItem as PostReplyItem
from .task import Task as Task
from _typeshed import Incomplete

__all__ = ['ACTIVE_DIRECTORY', 'ACTIVE_DIRECTORY_CONTACTS', 'AFFECTED_TASK_OCCURRENCES_CHOICES', 'ALL_OCCURRENCES', 'ALL_PROPERTIES', 'ALWAYS_OVERWRITE', 'ASSOCIATED', 'AUTO_RESOLVE', 'AcceptItem', 'BaseItem', 'BulkCreateResult', 'CONFERENCE_TYPES', 'CONFLICT_RESOLUTION_CHOICES', 'CONTACT_ITEM_CLASSES', 'CONTACTS', 'CONTACTS_ACTIVE_DIRECTORY', 'CalendarItem', 'CancelCalendarItem', 'Contact', 'DEFAULT', 'DELETE_TYPE_CHOICES', 'DeclineItem', 'DistributionList', 'ForwardItem', 'HARD_DELETE', 'ID_ONLY', 'ITEM_CLASSES', 'ITEM_TRAVERSAL_CHOICES', 'Item', 'MESSAGE_DISPOSITION_CHOICES', 'MESSAGE_ITEM_CLASSES', 'MOVE_TO_DELETED_ITEMS', 'TASK_ITEM_CLASSES', 'MeetingCancellation', 'MeetingRequest', 'MeetingResponse', 'Message', 'NEVER_OVERWRITE', 'Persona', 'PostItem', 'PostReplyItem', 'RegisterMixIn', 'ReplyAllToItem', 'ReplyToItem', 'SAVE_ONLY', 'SEARCH_SCOPE_CHOICES', 'SEND_AND_SAVE_COPY', 'SEND_MEETING_CANCELLATIONS_CHOICES', 'SEND_MEETING_INVITATIONS_AND_CANCELLATIONS_CHOICES', 'SEND_MEETING_INVITATIONS_CHOICES', 'SEND_ONLY', 'SEND_ONLY_TO_ALL', 'SEND_ONLY_TO_CHANGED', 'SEND_TO_ALL_AND_SAVE_COPY', 'SEND_TO_CHANGED_AND_SAVE_COPY', 'SEND_TO_NONE', 'SHALLOW', 'SHAPE_CHOICES', 'SOFT_DELETE', 'SOFT_DELETED', 'SPECIFIED_OCCURRENCE_ONLY', 'Task', 'TentativelyAcceptItem']

SHALLOW: str
SOFT_DELETED: str
ASSOCIATED: str
ITEM_TRAVERSAL_CHOICES: Incomplete
ACTIVE_DIRECTORY: str
ACTIVE_DIRECTORY_CONTACTS: str
CONTACTS: str
CONTACTS_ACTIVE_DIRECTORY: str
SEARCH_SCOPE_CHOICES: Incomplete
ITEM_CLASSES: Incomplete
TASK_ITEM_CLASSES: Incomplete
CONTACT_ITEM_CLASSES: Incomplete
MESSAGE_ITEM_CLASSES: Incomplete
