from ..configuration import Configuration as Configuration
from .protocol import AutodiscoverProtocol as AutodiscoverProtocol
from _typeshed import Incomplete
from collections.abc import Generator

log: Incomplete

def shelve_filename(): ...

AUTODISCOVER_PERSISTENT_STORAGE: Incomplete

def shelve_open_with_failover(file) -> Generator[Incomplete]: ...

class AutodiscoverCache:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, protocol) -> None: ...
    def __delitem__(self, key) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args, **kwargs) -> None: ...
    def __del__(self) -> None: ...

autodiscover_cache: Incomplete
