from ..properties import UserResponse as UserResponse
from ..protocol import BaseProtocol as BaseProtocol
from ..services import GetUserSettings as GetUserSettings
from ..transport import get_autodiscover_authtype as get_autodiscover_authtype
from ..version import Version as Version
from _typeshed import Incomplete

class AutodiscoverProtocol(BaseProtocol):
    TIMEOUT: int
    def __init__(self, config) -> None: ...
    @property
    def version(self): ...
    @property
    def auth_type(self): ...
    def get_auth_type(self): ...
    def get_user_settings(self, user, settings: Incomplete | None = None): ...
    def dummy_xml(self): ...
